group=me.earthme.luminol
version=1.21.8-R0.1-SNAPSHOT
mcVersion=1.21.8
release=1
# 0 for skip release, 1 for pre-release, 2 for release

foliaRef=7a1c5c7c7c86a0071654e03d7bf82120d113ef38

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
